### PR TITLE
Fix duplicate symbols on OS X fixes #36

### LINKED ISSUE #36: 'duplicate symbols for architecture x86_64' mac os x php7 link error
Building the extension fails on mac os x 10.11.4 with error
`duplicate symbols for architecture x86_64`

Output of the build log:

```
/bin/sh /Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/libtool --mode=compile cc  -I. -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman -DPHP_ATOM_INC -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/include -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/main -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/main -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/TSRM -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/Zend -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/ext -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O0 -Wall   -c /Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/php_gearman_client.c -o php_gearman_client.lo
 cc -I. -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman -DPHP_ATOM_INC -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/include -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/main -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/main -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/TSRM -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/Zend -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/ext -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O0 -Wall -c /Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/php_gearman_client.c  -fno-common -DPIC -o .libs/php_gearman_client.o
/bin/sh /Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/libtool --mode=compile cc  -I. -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman -DPHP_ATOM_INC -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/include -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/main -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/main -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/TSRM -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/Zend -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/ext -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O0 -Wall   -c /Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/php_gearman_task.c -o php_gearman_task.lo
 cc -I. -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman -DPHP_ATOM_INC -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/include -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/main -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/main -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/TSRM -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/Zend -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/ext -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O0 -Wall -c /Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/php_gearman_task.c  -fno-common -DPIC -o .libs/php_gearman_task.o
/bin/sh /Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/libtool --mode=link cc -DPHP_ATOM_INC -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/include -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/main -I/Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/main -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/TSRM -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/Zend -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/ext -I/Users/dbaltas/.phpbrew/php/php-7.0.3/include/php/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O0 -Wall   -o gearman.la -export-dynamic -avoid-version -prefer-pic -module -rpath /Users/dbaltas/.phpbrew/build/php-7.0.3/ext/gearman/modules  php_gearman.lo php_gearman_client.lo php_gearman_task.lo -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lgearman -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lgearman -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lgearman -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lgearman
cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/gearman.so -bundle  .libs/php_gearman.o .libs/php_gearman_client.o .libs/php_gearman_task.o  -L/usr/local/lib -lgearman  -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib
duplicate symbol _gearman_client_obj_handlers in:
    .libs/php_gearman.o
    .libs/php_gearman_client.o
duplicate symbol _gearman_client_ce in:
    .libs/php_gearman.o
    .libs/php_gearman_client.o
duplicate symbol _gearman_exception_ce in:
    .libs/php_gearman.o
    .libs/php_gearman_client.o
duplicate symbol _gearman_client_obj_handlers in:
    .libs/php_gearman.o
    .libs/php_gearman_task.o
duplicate symbol _gearman_task_obj_handlers in:
    .libs/php_gearman.o
    .libs/php_gearman_task.o
duplicate symbol _gearman_client_ce in:
    .libs/php_gearman.o
    .libs/php_gearman_task.o
duplicate symbol _gearman_exception_ce in:
    .libs/php_gearman.o
    .libs/php_gearman_task.o
duplicate symbol _gearman_task_ce in:
    .libs/php_gearman.o
    .libs/php_gearman_task.o
ld: 8 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [gearman.la] Error 1
```

Running cc with `-v` flag produced the same errors including some system details that may help

```
15:56:07 /tmp/pecl-gearman (master)$ cc -v ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/gearman.so -bundle  .libs/php_gearman.o .libs/php_gearman_client.o .libs/php_gearman_task.o  -L/usr/local/lib -lgearman  -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -bundle -flat_namespace -macosx_version_min 10.11.0 -undefined suppress -undefined suppress -o .libs/gearman.so -L/usr/local/lib .libs/php_gearman.o .libs/php_gearman_client.o .libs/php_gearman_task.o -lgearman -rpath /usr/local/lib -rpath /usr/local/lib -rpath /usr/local/lib -rpath /usr/local/lib -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin/libclang_rt.osx.a
```

### PR DESCRIPTION
**Pull request by xalopp**
While Linux seems to be OK, the test `tests/gearman_tasks_integration_test_002.phpt` fails for OS X: https://travis-ci.org/xalopp/pecl-gearman/jobs/160529849 

Maybe someone has some idea how to solves this completely?

### CODE REVIEW

**Comment by wcgallego** [comment]
hey @xalopp, sorry for radio silence on this. I've had a busy few weeks and any gearman work I've been handling has been either adding more tests or splitting up the php_gearman.c code to more logical separate files.

I did fix the same test as it was failing on my *nix machine. Can you give the latest on master a try to see if it resolves for you?

**Comment by xalopp** [comment]
`tests/gearman_tasks_integration_test_002.phpt` breaks now on Linux on Travis CI :(
https://travis-ci.org/xalopp/pecl-gearman/builds/175834537

**Comment by xalopp** [comment]
For OS X, the tests passes locally with this PR. I'm waiting for https://travis-ci.org/xalopp/pecl-gearman/jobs/175842702 to see how it's doing on Travis CI.

**Comment by wcgallego** [comment]
hey thanks for following through here. My rough guess would be a race condition in some of the responses. But just a guess

**Comment by xalopp** [comment]
@periklis could you take a look at this PR?

**Comment by periklis** [comment]
@xalopp seems fine for me. extern keyword is mandatory here to tell the compiler that decls have in the end the same and one definition.

**Comment by wcgallego** [comment]
finally getting a chance to test this out - looks good from my end!

@xalopp and @periklis - thanks for contributing and patience here. Much appreciated!

**Pull request merged**
